name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Light Snake
        run: |
          mkdir -p output
          curl -o output/github-contribution-grid-snake.svg \
            "https://raw.githubusercontent.com/Platane/snk/output/github-contribution-snake.svg?user=zzLeonn"

      - name: Generate Dark Snake
        run: |
          curl -o output/github-contribution-grid-snake-dark.svg \
            "https://raw.githubusercontent.com/Platane/snk/output/github-contribution-snake-dark.svg?user=zzLeonn"

      - name: Commit Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update contribution snake"
          file_pattern: output/*
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
